DROP TABLE IF EXISTS `#__petitions_signataires`;
CREATE TABLE `#__petitions_signataires` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `catid` int(11) NOT NULL default '0',
  `sid` int(11) NOT NULL default '0',
  `ip` varchar(15) NOT NULL default '',
  `organisation` varchar(100) NOT NULL default '',
  `title` varchar(20) NOT NULL default '',
  `alias` varchar(100) NOT NULL default '',
  `surname` varchar(100) NOT NULL default '',
  `name` varchar(100) NOT NULL default '',
  `age` varchar(30) default NULL,
  `profession` varchar(100) NOT NULL default '',
  `mail` varchar(50) default NULL,
  `url` varchar(100) NOT NULL default '',
  `localisation` varchar(100) default NULL,
  `localisation2` varchar(100) default NULL,
  `localisation3` varchar(100) default NULL,
  `localisation4` varchar(100) default NULL,
  `vote` int(10) default NULL,
  `comment` text,
  `edit` enum('y','n') NOT NULL default 'n',
  `date` datetime NOT NULL default '0000-00-00 00:00:00',
  `published` tinyint(1) NOT NULL default '0',
  `checked_out` int(11) NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `ordering` int(11) NOT NULL default '0',
  `archived` tinyint(1) NOT NULL default '0',
  `approved` tinyint(1) NOT NULL default '1',
  `params` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `catid` (`catid`,`published`,`archived`)
) ENGINE=MyISAM ;