<?php
//Joomla Petitions v 1.5 //
/**
* @ Package Joomla Petitions
* @ Copyright (C) 2007 - 2008 Milos Colic - All rights reserved
* @ Powered by Milos Colic - www.joomlapetitions.com
* @ All rights reserved
* @ Joomla Petitions Component is Free Software
* @ Released under GNU/GPL License : http://www.gnu.org/copyleft/gpl.html
*/
//TODO country list
?>
<option value="" selected="selected">-----------  Select your country  -----------
<option value=ad>Andorre
<option value=af>Afghanistan
<option value=za>Afrique du Sud
<option value=al>Albanie
<option value=dz>Alg&eacute;rie
<option value=de>Allemagne
<option value=ao>Angola
<option value=aq>Antarctique
<option value=sa>Arabie Saoudite
<option value=ar>Argentine
<option value=am>Arm&eacute;nie
<option value=au>Australie
<option value=at>Autriche
<option value=az>Azerba&iuml;djan
<option value=bs>Bahamas
<option value=bh>Bahre&iuml;n
<option value=bd>Bangladesh
<option value=bb>Barbade
<option value=be>Belgique
<option value=bz>Belize
<option value=bj>B&eacute;nin
<option value=bm>Bermudes
<option value=bt>Bhoutan
<option value=by>Bi&eacute;lorussie
<option value=bo>Bolivie
<option value=ba>Bosnie Herz&eacute;govine
<option value=bw>Botswana
<option value=br>Br&eacute;sil
<option value=bn>Brun&eacute;i Darussalam
<option value=bg>Bulgarie
<option value=bf>Burkina Faso
<option value=bi>Burundi
<option value=kh>Cambodge
<option value=cm>Cameroun
<option value=ca>Canada
<option value=cv>Cap Vert
<option value=cl>Chili
<option value=cn>Chine
<option value=cy>Chypre
<option value=co>Colombie
<option value=km>Comores
<option value=cg>Congo
<option value=cd>Congo (R&eacute;publique d&eacute;mocratique)
<option value=kr>Cor&eacute;e (R&eacute;publique de )
<option value=kp>Cor&eacute;e (R&eacute;publique populaire d&eacute;mocratique de)
<option value=cr>Costa Rica
<option value=ci>C�te d'Ivoire
<option value=hr>Croatie
<option value=cu>Cuba
<option value=dk>Danemark
<option value=dj>Djibouti
<option value=eg>Egypte
<option value=sv>El Salvador
<option value=ae>Emirats Arabes Unis
<option value=ec>Equateur
<option value=es>Espagne
<option value=ee>Estonie
<option value=us>Etats-Unis
<option value=et>Ethiopie
<option value=fi>Finlande
<option value=fr>France
<option value=ga>Gabon
<option value=gm>Gambie
<option value=ge>G&eacute;orgie
<option value=gh>Ghana
<option value=gi>Gibraltar
<option value=gr>Gr&agrave;ce
<option value=gl>Groenland
<option value=gp>Guadeloupe
<option value=gt>Guatemala
<option value=gn>Guin&eacute;e
<option value=gq>Guin&eacute;e &eacute;quatoriale
<option value=gw>Guin&eacute;e-Bissau
<option value=gy>Guyana
<option value=gf>Guyane fran�aise
<option value=ht>Ha&iuml;ti
<option value=hn>Honduras
<option value=hk>Hong-Kong
<option value=hu>Hongrie
<option value=f�>Iles F&eacute;ro&eacute;
<option value=in>Inde
<option value=id>Indon&eacute;sie
<option value=iq>Irak
<option value=ir>Iran
<option value=ie>Irlande
<option value=is>Islande
<option value=il>Isra�l
<option value=it>Italie
<option value=jm>Jama&iuml;que
<option value=jp>Japon
<option value=jo>Jordanie
<option value=kz>Kazakhstan
<option value=ke>Kenya
<option value=kg>Kirghizistan
<option value=kw>Kowe&iuml;t
<option value=la>Laos (R&eacute;publique d&eacute;mocratique populaire Lao)
<option value=ls>Lesotho
<option value=lv>Lettonie
<option value=lb>Liban
<option value=lr>Liberia
<option value=li>Liechtenstein
<option value=lt>Lituanie
<option value=lu>Luxembourg
<option value=mo>Macao
<option value=mk>Mac&eacute;doine
<option value=mg>Madagascar
<option value=my>Malaisie
<option value=mw>Malawi
<option value=mv>Maldives
<option value=ml>Mali
<option value=mt>Malte
<option value=ma>Maroc
<option value=mq>Martinique
<option value=mu>Maurice
<option value=mr>Mauritanie
<option value=mx>Mexique
<option value=md>Moldavie
<option value=mc>Monaco
<option value=mn>Mongolie
<option value=me>Mont&eacute;n&eacute;gro
<option value=mz>Mozambique
<option value=na>Namibie
<option value=np>N&eacute;pal
<option value=ni>Nicaragua
<option value=ne>Niger
<option value=ng>Nig&eacute;ria
<option value=no>Norv&agrave;ge
<option value=nc>Nouvelle-Cal&eacute;donie
<option value=nz>Nouvelle-Z&eacute;lande
<option value=ug>Ouganda
<option value=uz>Ouzb&eacute;kistan
<option value=pk>Pakistan
<option value=pa>Panama
<option value=pg>Papouasie-Nouvelle-Guin&eacute;e
<option value=py>Paraguay
<option value=nl>Pays-Bas
<option value=pe>P&eacute;rou
<option value=ph>Philippines
<option value=pl>Pologne
<option value=pf>Polyn&eacute;sie fran�aise
<option value=pr>Porto Rico
<option value=pt>Portugal
<option value=qc>Qu&eacute;bec
<option value=cf>R&eacute;publique centrafricaine
<option value=dd>R&eacute;publique d&eacute;mocratique allemande [RDA] (1949-1990)
<option value=do>R&eacute;publique Dominicaine
<option value=cz>R&eacute;publique Tch&agrave;que
<option value=ro>Roumanie
<option value=gb>Royaume-Uni
<option value=ru>Russie
<option value=rw>Rwanda
<option value=sm>Saint-Marin
<option value=sb>Salomon (Iles)
<option value=sn>S&eacute;n&eacute;gal
<option value=rs>Serbie
<option value=cs>Serbie-et-Mont&eacute;n&eacute;gro
<option value=sc>Seychelles
<option value=sl>Sierra Leone
<option value=sg>Singapour
<option value=sk>Slovaquie
<option value=si>Slov&eacute;nie
<option value=so>Somalie
<option value=sd>Soudan
<option value=lk>Sri Lanka
<option value=se>Su&agrave;de
<option value=ch>Suisse
<option value=sr>Suriname
<option value=sz>Swaziland
<option value=sy>Syrie
<option value=tj>Tadjikistan
<option value=tw>Ta&iuml;wan
<option value=tz>Tanzanie
<option value=td>Tchad
<option value=ps>Territoires palestiniens
<option value=th>Tha&iuml;lande
<option value=tg>Togo
<option value=tt>Trinit&eacute;-et-Tobago
<option value=tn>Tunisie
<option value=tm>Turkmenistan
<option value=tr>Turquie
<option value=ua>Ukraine
<option value=su>Union Sovi&eacute;tique
<option value=uy>Uruguay
<option value=va>Vatican
<option value=ve>Venezuela
<option value=vn>Vietnam
<option value=ye>Y&eacute;men
<option value=yu>Yougoslavie
<option value=zr>Za&iuml;re
<option value=zm>Zambie
<option value=zw>Zimbabwe
